version: '3.8'

name: pregs-rateio-dev

services:
  mongo:
    image: mongo:7.0.9
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: pregsrateio
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: development
    volumes:
      - mongo_data:/data/db
    networks:
      - pregs_net

  backend:
    image: brunorsch/pregs-rateio-server:1.0.0
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MONGO_DEV_URL: mongodb://root:development@mongo:27017/pregsrateio?authSource=admin
    networks:
      - pregs_net

volumes:
  mongo_data:

networks:
  pregs_net:
    driver: bridge
