micronaut:
  security:
    intercept-url-map:
      - pattern: /docs/**
        http-method: GET
        access: isAnonymous()
      - pattern: /swagger/**
        http-method: GET
        access: isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access: isAnonymous()
      - pattern: /**
        access: isAuthenticated()

#logger:
#  levels:
#    io.micronaut.security: DEBUG
#    io.micronaut.http.filter: DEBUG
#    io.micronaut.security.filters: DEBUG
#    io.micronaut.security.token: DEBUG
#    io.micronaut.security.token.jwt: DEBUG